"""
Generates an EAD3 (Encoded Archival Description, version 3) finding aid
from a classified sentence list produced by the role-classification pipeline.

The output conforms to the EAD3 XML schema maintained by the Society of
American Archivists and the Library of Congress.
  Schema: https://www.loc.gov/ead/ead3.xsd
  Tag Library: https://www.loc.gov/ead/EAD3taglib/

@author: Archival Rights Role Classifier Development Team
"""

import re
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from xml.dom import minidom


# ---------- role → EAD component mapping ----------
# Each rhetorical role maps to an EAD3 <c> (component) with a semantic @level
# and to a <head> label used inside <scopecontent>.
_ROLE_EAD_MAP = {
    "Finding":    {"level": "subseries", "head": "Findings of Fact"},
    "Legal Rule": {"level": "subseries", "head": "Applicable Legal Rules"},
    "Reasoning":  {"level": "subseries", "head": "Board Reasoning"},
    "Evidence":   {"level": "subseries", "head": "Evidentiary Record"},
    "Citation":   {"level": "subseries", "head": "Legal Citations"},
    "Sentence":   {"level": "subseries", "head": "General Narrative"},
    "UNCERTAIN":  {"level": "subseries", "head": "Uncertain Classifications (Requires Review)"},
}

# Presentation order — archival logic: law → facts → evidence → reasoning → citations → general
_ROLE_ORDER = ["Legal Rule", "Finding", "Evidence", "Reasoning", "Citation", "Sentence", "UNCERTAIN"]


def _sanitize(text: str) -> str:
    """Strip control characters that are invalid in XML 1.0."""
    return re.sub(r'[\x00-\x08\x0b\x0c\x0e-\x1f]', '', text)


def generate_ead(classified_sentences: list, title: str = "", decision_date: str = "") -> str:
    """
    Build a valid EAD3 XML finding aid from classified sentences.

    Parameters
    ----------
    classified_sentences : list[dict]
        Each dict has keys: sentence, role, suggested_role, prob, entropy, uncertain.
        This is the same list returned by the /doc endpoint.
    title : str, optional
        Document title (e.g., "BVA Decision 1302554")
    decision_date : str, optional
        Original decision date (e.g., "2013-01-23")

    Returns
    -------
    str
        Pretty-printed EAD3 XML string.
    """

    ns = "http://ead3.archivists.org/schema/"
    ET.register_namespace('', ns)

    ead = ET.Element('ead', xmlns=ns)

    # ── <control> ──
    control = ET.SubElement(ead, 'control')

    recordid = ET.SubElement(control, 'recordid')
    slug = re.sub(r'\W+', '-', title.lower()).strip('-') if title else 'auto-generated'
    recordid.text = f"finding-aid-{slug}"

    filedesc = ET.SubElement(control, 'filedesc')
    titlestmt = ET.SubElement(filedesc, 'titlestmt')
    titleproper = ET.SubElement(titlestmt, 'titleproper')
    titleproper.text = title or "AI-Assisted Finding Aid — Legal Decision"

    notestmt = ET.SubElement(filedesc, 'notestmt')
    note = ET.SubElement(notestmt, 'controlnote')
    note_p = ET.SubElement(note, 'p')
    note_p.text = (
        "This finding aid was auto-generated by a legal sentence role "
        "classification system (LegalBERT + LSTM). Uncertain classifications "
        "are flagged for mandatory archivist review."
    )

    ms = ET.SubElement(control, 'maintenancestatus', value='new')
    ma = ET.SubElement(control, 'maintenanceagency')
    agencyname = ET.SubElement(ma, 'agencyname')
    agencyname.text = "Archival Rights Role Classifier"

    mh = ET.SubElement(control, 'maintenancehistory')
    me = ET.SubElement(mh, 'maintenanceevent')
    ET.SubElement(me, 'eventtype', value='created')
    edt = ET.SubElement(me, 'eventdatetime',
                        standarddatetime=datetime.now(timezone.utc).isoformat())
    edt.text = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    ET.SubElement(me, 'agenttype', value='machine')
    agent = ET.SubElement(me, 'agent')
    agent.text = "Legal Sentence Role Classifier (LegalBERT + Bi-LSTM)"

    # ── <archdesc> ──
    archdesc = ET.SubElement(ead, 'archdesc', level='file')

    did = ET.SubElement(archdesc, 'did')
    unittitle = ET.SubElement(did, 'unittitle')
    unittitle.text = title or "Board of Veterans' Appeals Decision"
    if decision_date:
        unitdate = ET.SubElement(did, 'unitdate', unitdatetype='inclusive')
        unitdate.text = decision_date

    abstract = ET.SubElement(did, 'abstract')
    n_total = len(classified_sentences)
    n_uncertain = sum(1 for s in classified_sentences if s.get('uncertain'))
    abstract.text = (
        f"Machine-classified finding aid containing {n_total} segmented sentences. "
        f"{n_uncertain} sentence(s) flagged as uncertain (entropy-based) "
        f"requiring archivist review before archival commitment."
    )

    # -- arrangement note --
    arrangement = ET.SubElement(archdesc, 'arrangement')
    arr_head = ET.SubElement(arrangement, 'head')
    arr_head.text = "Arrangement"
    arr_p = ET.SubElement(arrangement, 'p')
    arr_p.text = (
        "Sentences are organised by their AI-predicted rhetorical role: "
        "Legal Rule, Finding, Evidence, Reasoning, Citation, "
        "General Narrative, and Uncertain (flagged for review). "
        "Within each role group, sentences appear in their original document order."
    )

    # -- processing info --
    processinfo = ET.SubElement(archdesc, 'processinfo')
    pi_head = ET.SubElement(processinfo, 'head')
    pi_head.text = "Processing Information"
    pi_p = ET.SubElement(processinfo, 'p')
    pi_p.text = (
        "Classification performed by a bidirectional LSTM trained on the "
        "VetClaims-JSON corpus with Dice Loss. Sentence embeddings produced "
        "by LegalBERT (nlpaueb/legal-bert-base-uncased). Uncertainty estimated "
        "via Shannon entropy over the 6-class softmax distribution; sentences "
        "with max probability below 0.65 are flagged UNCERTAIN."
    )

    # ── <dsc> — Description of Subordinate Components ──
    dsc = ET.SubElement(archdesc, 'dsc', dsctype='combined')

    # Group sentences by role, preserving document order
    role_groups: dict[str, list] = {role: [] for role in _ROLE_ORDER}
    for idx, s in enumerate(classified_sentences):
        role = s.get('role', 'Sentence')
        if role not in role_groups:
            role_groups[role] = []
        role_groups[role].append((idx, s))

    for role in _ROLE_ORDER:
        sentences = role_groups.get(role, [])
        if not sentences:
            continue

        meta = _ROLE_EAD_MAP.get(role, {"level": "subseries", "head": role})

        c = ET.SubElement(dsc, 'c', level=meta['level'])
        c_did = ET.SubElement(c, 'did')
        c_title = ET.SubElement(c_did, 'unittitle')
        c_title.text = meta['head']

        c_scope = ET.SubElement(c, 'scopecontent')
        c_head = ET.SubElement(c_scope, 'head')
        c_head.text = f"{meta['head']} ({len(sentences)} sentence{'s' if len(sentences) != 1 else ''})"

        for doc_idx, s in sentences:
            p = ET.SubElement(c_scope, 'p')
            text = _sanitize(s.get('sentence', ''))

            # Encode classification metadata as attributes for machine readability
            p.set('id', f"s{doc_idx}")
            p.set('altrender', f"prob={s.get('prob', 0)};entropy={s.get('entropy', 0)}")

            if s.get('uncertain'):
                suggested = s.get('suggested_role', role)
                p.text = f"[UNCERTAIN — suggested: {suggested}] {text}"
            else:
                p.text = text

    # ── serialize ──
    rough = ET.tostring(ead, encoding='unicode', xml_declaration=False)
    dom = minidom.parseString(rough)
    pretty = dom.toprettyxml(indent="  ", encoding=None)
    # Remove extra blank lines minidom inserts
    lines = [line for line in pretty.split('\n') if line.strip()]
    return '\n'.join(lines)
